cmake_minimum_required(VERSION 4.0)
project(c__)

set(CMAKE_CXX_STANDARD 14)

include_directories(.)

add_executable(c__
        Untitled-1.cpp
        Untitled-10.cpp
        Untitled-11.cpp
        Untitled-12.cpp
        Untitled-13.cpp
        Untitled-14.cpp
        Untitled-15.cpp
        Untitled-16.cpp
        Untitled-17.cpp
        Untitled-18.cpp
        Untitled-19.cpp
        Untitled-2.cpp
        Untitled-20.cpp
        Untitled-21.cpp
        Untitled-22.cpp
        Untitled-23.cpp
        Untitled-24.cpp
        Untitled-25.cpp
        Untitled-26.cpp
        Untitled-27.cpp
        Untitled-3.cpp
        Untitled-4.cpp
        Untitled-5.cpp
        Untitled-6.cpp
        Untitled-7.cpp
        Untitled-8.cpp
        Untitled-9.cpp)
